### ISSUE TITLE
Link is missing

### ISSUE THREAD

**Issue by gavr123456789** [coanda/dactl#20]
The [link ](https://github.com/coanda/dactl/blob/master/docs/source/assets/sample-config.xml)to the configuration file from the [manual ](https://dactl.readthedocs.io/en/latest/intro.html)is missing.

**Comment by geoffjay** [comment]
This has been fixed. For what it's worth there's a lot in that configuration including the use of this plugin https://github.com/geoffjay/dactl-plugin-arduino-udp that's not very well documented.
